/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
    "node_modules/daisyui/dist/**/*.js",
    "node_modules/react-daisyui/dist/**/*.js",
  ],
  theme: {
    extend: {},
  },
  darkMode: "class",
  plugins: [
    require("daisyui"),
    require("react-daisyui"),
    require("tailwind-children"),
    require("@tailwindcss/typography"),
  ],
  daisyui: {
    styled: true,
    themes: [
      {
        light: {
          primary: "#88C0D0",
          "primary-focus": "#81A1C1",
          "primary-content": "#2E3440",
          secondary: "#5E81AC",
          "secondary-focus": "#BF616A",
          "secondary-content": "#ECEFF4",
          accent: "#8FBCBB",
          "accent-focus": "#88C0D0",
          "accent-content": "#2E3440",
          neutral: "#3B4252",
          "neutral-focus": "#434C5E",
          "neutral-content": "#ECEFF4",
          "base-100": "#D8DEE9",
          "base-200": "#E5E9F0",
          "base-300": "#ECEFF4",
          "base-content": "#2E3440",
          info: "#88C0D0",
          success: "#A3BE8C",
          warning: "#EBCB8B",
          error: "#BF616A",
        },
      },
      {
        dark: {
          primary: "#88C0D0",
          "primary-focus": "#60a5fa",
          "primary-content": "#ECEFF4",
          secondary: "#c084fc",
          "secondary-focus": "#BF616A",
          "secondary-content": "#2E3440",
          accent: "#8FBCBB",
          "accent-focus": "#88C0D0",
          "accent-content": "#ECEFF4",
          neutral: "#3B4252",
          "neutral-focus": "#434C5E",
          "neutral-content": "#D8DEE9",
          "base-100": "#242933",
          "base-200": "#3B4252",
          "base-300": "#434C5E",
          "base-content": "#D8DEE9",
          info: "#88C0D0",
          success: "#A3BE8C",
          warning: "#EBCB8B",
          error: "#f43f5e",
        },
      },
    ],
  },

  reactStrictMode: true,
};
